default:
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
  cache:
    paths:
      - .cache/pip
  

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


stages:
  - lint
  - test

flake8:
  stage: lint
  script:
    - flake8 src/
  allow_failure: false
  tags:
    - linux
    - python
