default:
  image: python:3.9
  before_script:
    - pip install -r requirements.txt

stages:
  - lint
  - test

flake8:
  stage: lint
  script:
    - flake8 src/
    - flake8 tests/
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  allow_failure: false
  tags:
    - linux
    - python

run_tests:
  stage: test
  script:
    - export PYTHONPATH=$CI_PROJECT_DIR
    - pytest tests/ --junitxml=test-reports/report.xml --cov=src --cov-report=xml --cov-report=html
  artifacts:
    when: always
    paths:
      - test-reports/         
      - htmlcov/              
      - coverage.xml        
    reports:
      junit: test-reports/report.xml 
  tags:
    - linux
    - python
